{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "tools.fullname" . }}-ingress
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "tools.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - host: {{ .Values.ingress.host | quote }}
      http:
        paths:
          {{- if .Values.api.enabled }}
          - path: {{ .Values.api.pathPrefix }}
            pathType: Prefix
            backend:
              service:
                name: {{ include "tools.fullname" . }}-api
                port:
                  number: {{ .Values.api.service.port }}
          {{- end }}
          {{- if .Values.frontend.enabled }}
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "tools.fullname" . }}-frontend
                port:
                  number: {{ .Values.frontend.service.port }}
          {{- end }}
{{- end }}
